### ISSUE TITLE
BUG: Textract log doesn't capture enough detail

### ISSUE THREAD

**Issue by csmcallister** [GSA/fbo-scraper#72]
For the 12/17/18 run, textract failed on three docs even though textract works on those docs locally. Unfortunately, the traceback wasn't logged, so we can't diagnose.

## Expected Behavior
If textract fails on a doc, the logs should tell us both the url and name of the doc in addition to the full traceback.

## Current Behavior
When textract fails on a doc, it just logs the attachment url.

## Possible Solution
 - [ ] Add the file name and the full traceback to the log.
 - [ ] Wait for this to happen again and then attempt to solve.

## Steps to Reproduce (for bugs)
See the log [here](https://logs.fr.cloud.gov/app/kibana#/dashboard/App-Overview?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logs-app*',key:'@cf.app',negate:!f,params:(query:srt-fbo-scraper,type:phrase),type:phrase,value:srt-fbo-scraper),query:(match:('@cf.app':(query:srt-fbo-scraper,type:phrase))))),fullScreenMode:!f,options:(darkTheme:!f,useMargins:!f),panels:!((embeddableConfig:(vis:(legendOpen:!t)),gridData:(h:5,i:'1',w:36,x:0,y:0),id:App-links,panelIndex:'1',type:visualization,version:'6.3.2'),(gridData:(h:10,i:'2',w:36,x:0,y:5),id:'App-logs-by-source-type-(top-10)',panelIndex:'2',type:visualization,version:'6.3.2'),(embeddableConfig:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),gridData:(h:15,i:'3',w:12,x:36,y:0),id:App-names,panelIndex:'3',type:visualization,version:'6.3.2'),(columns:!('@cf.org','@cf.space','@cf.app','@source.job','@source.component','@source.type','@level','@message'),gridData:(h:25,i:'4',w:48,x:0,y:15),id:app-all-overview,panelIndex:'4',sort:!('@timestamp',desc),type:search,version:'6.3.2')),query:(language:lucene,query:'*Exception%20occurred'),timeRestore:!f,title:'App%20-%20Overview',viewMode:view))

## Context
Adding this functionality to the logs will improve our ability to capture all of the attachments and their text.

**Comment by csmcallister** [comment]
On 12/13/18's run, textract failed on 3 docs. In all cases, the traceback shows that there was an error with `antiword`:

```
[ERROR] Exception occurred textracting attachments/Section_E_Draft.doc from 
https://www.fbo.gov/utils/view?id=bed0f0a8fb4b446476d1e51adab2dcae:  
The command `antiword attachments/Section_E_Draft.doc` failed with exit code 1
```

Before trying to figure out a solution, I'll add a test_doc.doc to our test fixtures so that the solution can be tried in the CI environment (don't want to rely on my local installation of antiword).

**Comment by csmcallister** [comment]
First attempt at a solution was to ensure that the cloud.gov environment and CI docker image were the same. Although the test passed for the .doc in Docker, the app continues to fail on `.doc` files:

```
time="2018-12-14T04:00:29Z" level=info msg="[ERROR] Exception occurred textracting 
attachments/RFQ-Commercial_Brand_Name_or_Equal.doc from https://www.fbo.gov/utils/view?
id=aafbaa098734b92e4381d430f73465dc:                               The command `antiword 
attachments/RFQ-Commercial_Brand_Name_or_Equal.doc` failed with exit code 1" channel=stderr 
iteration=0 job.command="/usr/bin/env python3 /home/vcap/app/fbo.py" job.position=0 
job.schedule="0 4 * * *"
```

Will need to do some more research.

**Comment by csmcallister** [comment]
Traceback with antiword's error message.
```
byte_string = self.extract(filename, **kwargs)
b_text = process(file_name)
File "/home/vcap/app/utils/textract/textract/parsers/doc_parser.py", line 9, in extract
File "/home/vcap/app/utils/get_fbo_attachments.py", line 72, in get_attachment_text
return parser.process(filename, encoding, **kwargs)
/home/vcap/app/utils/textract/textract/parsers/utils.py", line 46, in process
Traceback (most recent call last):
File "/home/vcap/app/utils/textract/textract/parsers/__init__.py", line 76, in process
"b"I can't open your mapping file (UTF-8.txt)\nIt is not in '/home/vcap/app/.antiword' nor in '/usr/share/antiword'.\n\tName: antiword\n\tPurpose: Display MS-Word files\n\tAuthor: (C) 1998-2005 Adri van Os\n\tVersion: 0.37  (21 Oct 2005)\n\tStatus: GNU General Public License\n\tUsage: antiword [switches] wordfile1 [wordfile2 ...]\n\tSwitches: [-f|-t|-a papersize|-p papersize|-x dtd][-m mapping][-w #][-i #][-Ls]\n\t\t-f formatted text output\n\t\t-t text output (default)\n\t\t-a <paper size name> Adobe PDF output\n\t\t-p <paper size name> PostScript output\n\t\t   paper size like: a4, letter or legal\n\t\t-x <dtd> XML output\n\t\t   like: db (DocBook)\n\t\t-m <mapping> character mapping file\n\t\t-w <width> in characters of text output\n\t\t-i <level> image level (PostScript only)\n\t\t-L use landscape mode (PostScript only)\n\t\t-r Show removed text\n\t\t-s Show hidden (by Word) text\n
stdout, stderr = self.run(['antiword', filename])
"b''------------- stderr -------------"
' '.join(args), pipe.returncode, stdout, stderr,
File "/home/vcap/app/utils/textract/textract/parsers/utils.py", line 105, in run
b''------------- stderr -------------
```

**Comment by csmcallister** [comment]
A possible solution is to execute antiword using an explicit mapping, like `8859-1` (i.e.  Latin-1) or `utf-8`:
`$ antiword -m utf-8 file.doc`
It works locally.

**Comment by csmcallister** [comment]
Log now shows that `unrtf` has failed
```
Exception occurred textracting attachments/Attachment_5_-_DRAFT_Past_Performance_Questionnaire.rtf from https://www.fbo.gov/utils/view?
id=cf5da68ff6922c2af14545e4e1db6488:                               The command `unrtf --text 
attachments/Attachment_5_-_DRAFT_Past_Performance_Questionnaire.rtf` failed with exit code 1
```

**Comment by csmcallister** [comment]
According to antiword's [documentation](https://linux.die.net/man/1/antiword):
```
Antiword looks for its mapping files in three directories, in the order given:
(1) The directory specified by $ANTIWORDHOME
(2) The directory specified by $HOME/.antiword
(3) Directory /usr/share/antiword
```
From the logs, we can see that antiword is trying to look into `/home/vcap/app/.antiword`. But after ssh'ing into the app, I can verify that the `/home/vcap/app/.antiword` does not exist. 

A solution could involve downloading antiword's source and placing it where it needs to belong. Something like:

`wget -P /home/vcap/app/.antiword/ http://www.winfield.demon.nl/linux/antiword-0.37.tar.gz && tar xvzf /home/vcap/app/.antiword/antiword-0.37.tar.gz && rm /home/vcap/app/.antiword/antiword-0.37.tar.gz`

This could get added to the command option in `manifest.yml`.

**Comment by csmcallister** [comment]
antiword will work now that textract is no longer vendored
