### ISSUE TITLE
BUG: Textract raises codec error with some but not all pdfs

### ISSUE THREAD

**Issue by csmcallister** [GSA/fbo-scraper#92]
Textract raises a codec error when processing a pdf. 

## Expected Behavior
Works as expected. But, although this error isn't critical, it might be able to be addressed.

## Current Behavior
```
File "/home/vcap/app/utils/textract/textract/parsers/utils.py", line 67, in decode
b_text = process(file_name)
unicode_string = self.decode(byte_string)
return parser.process(filename, encoding, **kwargs)
[ERROR] Exception occurred textracting attachments/RFQ_Attachment_FAR_52.212-5.pdf from 
https://www.fbo.gov/utils/view?id=b459300e5d166f065d23ea175daa537c:                           
    'charmap' codec can't decode byte 0x9d in position 17242: character maps to 
\u003cundefined\u003e
File "/home/vcap/app/utils/get_fbo_attachments.py", line 72, in get_attachment_text
File \"/home/vcap/deps/1/python/lib/python3.6/encodings/cp1254.py
return codecs.charmap_decode(input,errors,decoding_table
return text.decode(result['encoding'])
File /home/vcap/app/utils/textract/textract/parsers/utils.py", line 47, in process
Traceback (most recent call last):\" channel=stderr iteration=0 job.command=\"/usr/bin/env python3 /home/vcap/app/fbo.py
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 17242: character maps to <undefined>
 File "/home/vcap/app/utils/textract/textract/parsers/__init__.py", line 76, in process
```

## Possible Solution
check to be sure that the file is being opened in binary mode. Also manually check the file's encoding.

**Comment by csmcallister** [comment]
Closing since unvendoring textract solved.
